// NFR Metadata Index - Complete 85 NFRs
// Based on Frontend + Backend Non-Functional Requirements Master Checklist

import type { NFRMetadata, NFRCategory } from "@/types/nfr";

// Complete NFR Collection: 30 Frontend + 30 Backend + 15 Shared + 10 Advanced = 85 Total
export const NFR_METADATA: NFRMetadata[] = [
  // ============================================
  // 🟦 FRONTEND NFRs (1-30)
  // ============================================
  {
    id: 1,
    title: "Page Load Performance",
    slug: "page-load-performance",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["performance", "core-web-vitals", "lcp", "fcp", "tti"],
    relatedNFRs: [2, 3, 61],
    readTime: 8,
    importance: "critical",
    tldr: "Optimize initial page load times targeting sub-3s LCP and sub-1.8s FCP through code splitting, resource optimization, and critical rendering path improvements.",
  },
  {
    id: 2,
    title: "Perceived Performance",
    slug: "perceived-performance",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["performance", "ux", "skeleton", "optimistic-ui", "loading"],
    relatedNFRs: [1, 3, 14],
    readTime: 7,
    importance: "high",
    tldr: "Enhance user perception of speed through skeleton screens, optimistic updates, progressive loading, and instant feedback patterns.",
  },
  {
    id: 3,
    title: "Rendering Strategy",
    slug: "rendering-strategy",
    category: "frontend",
    difficulty: "advanced",
    tags: ["ssr", "ssg", "isr", "csr", "hydration"],
    relatedNFRs: [1, 2, 13],
    readTime: 10,
    importance: "critical",
    tldr: "Choose optimal rendering strategies (SSR, SSG, ISR, CSR) based on content type, SEO needs, and interactivity requirements.",
  },
  {
    id: 4,
    title: "Virtualization / Windowing",
    slug: "virtualization-windowing",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["performance", "lists", "virtual-scroll", "windowing", "large-data"],
    relatedNFRs: [1, 2, 76],
    readTime: 8,
    importance: "high",
    tldr: "Implement virtual scrolling and windowing techniques to efficiently render large lists and tables without DOM bloat.",
  },
  {
    id: 5,
    title: "Media Optimization",
    slug: "media-optimization",
    category: "frontend",
    difficulty: "beginner",
    tags: ["images", "video", "webp", "avif", "lazy-loading", "responsive"],
    relatedNFRs: [1, 7, 8],
    readTime: 7,
    importance: "high",
    tldr: "Optimize images and media with modern formats (WebP, AVIF), responsive sizing, lazy loading, and CDN delivery.",
  },
  {
    id: 6,
    title: "Offline Support / PWA",
    slug: "offline-support-pwa",
    category: "frontend",
    difficulty: "advanced",
    tags: ["pwa", "service-worker", "offline", "cache-api", "installable"],
    relatedNFRs: [7, 20, 8],
    readTime: 12,
    importance: "medium",
    tldr: "Build Progressive Web Apps with service workers, offline-first architecture, and installable experiences.",
  },
  {
    id: 7,
    title: "Client & Edge Caching",
    slug: "client-edge-caching",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["caching", "cdn", "cache-control", "etag", "stale-while-revalidate"],
    relatedNFRs: [6, 8, 69],
    readTime: 9,
    importance: "high",
    tldr: "Implement multi-layer caching with browser cache, CDN edge caching, and service worker caching for optimal performance.",
  },
  {
    id: 8,
    title: "Network Efficiency",
    slug: "network-efficiency",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["network", "compression", "http2", "prefetch", "preconnect"],
    relatedNFRs: [1, 7, 5],
    readTime: 8,
    importance: "high",
    tldr: "Minimize network overhead with compression, HTTP/2, resource hints, request batching, and efficient data fetching.",
  },
  {
    id: 9,
    title: "Accessibility (a11y)",
    slug: "accessibility",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["a11y", "wcag", "aria", "screen-reader", "keyboard"],
    relatedNFRs: [10, 11, 80],
    readTime: 12,
    importance: "critical",
    tldr: "Ensure WCAG 2.1 AA compliance with semantic HTML, ARIA attributes, keyboard navigation, and screen reader support.",
  },
  {
    id: 10,
    title: "Cross-Browser Compatibility",
    slug: "cross-browser-compatibility",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["browsers", "polyfills", "feature-detection", "progressive-enhancement"],
    relatedNFRs: [9, 11, 79],
    readTime: 7,
    importance: "high",
    tldr: "Ensure consistent functionality across browsers with feature detection, polyfills, and progressive enhancement.",
  },
  {
    id: 11,
    title: "Device Responsiveness",
    slug: "device-responsiveness",
    category: "frontend",
    difficulty: "beginner",
    tags: ["responsive", "mobile-first", "breakpoints", "touch", "viewport"],
    relatedNFRs: [9, 10, 77],
    readTime: 7,
    importance: "critical",
    tldr: "Build mobile-first responsive layouts that adapt across devices with proper touch targets and viewport handling.",
  },
  {
    id: 12,
    title: "Internationalization & Localization",
    slug: "internationalization-localization",
    category: "frontend",
    difficulty: "advanced",
    tags: ["i18n", "l10n", "rtl", "translations", "locale"],
    relatedNFRs: [9, 11, 67],
    readTime: 10,
    importance: "medium",
    tldr: "Support multiple languages and locales with proper text extraction, RTL layouts, and locale-aware formatting.",
  },
  {
    id: 13,
    title: "SEO & Discoverability",
    slug: "seo-discoverability",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["seo", "meta-tags", "structured-data", "sitemap", "crawlability"],
    relatedNFRs: [3, 1, 72],
    readTime: 9,
    importance: "high",
    tldr: "Optimize for search engines with proper meta tags, structured data, semantic HTML, and crawlable content.",
  },
  {
    id: 14,
    title: "Error UX & Recovery",
    slug: "error-ux-recovery",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["errors", "error-boundaries", "retry", "fallback", "user-feedback"],
    relatedNFRs: [2, 64, 23],
    readTime: 8,
    importance: "high",
    tldr: "Provide graceful error handling with clear messages, recovery options, and error boundaries for better UX.",
  },
  {
    id: 15,
    title: "XSS & Injection Protection",
    slug: "xss-injection-protection",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["security", "xss", "csp", "sanitization", "injection"],
    relatedNFRs: [16, 18, 62],
    readTime: 9,
    importance: "critical",
    tldr: "Prevent XSS attacks with Content Security Policy, input sanitization, and safe DOM manipulation practices.",
  },
  {
    id: 16,
    title: "Secure Client Storage",
    slug: "secure-client-storage",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["security", "storage", "encryption", "cookies", "localstorage"],
    relatedNFRs: [15, 17, 45],
    readTime: 7,
    importance: "high",
    tldr: "Securely store sensitive data client-side with encryption, httpOnly cookies, and proper storage selection.",
  },
  {
    id: 17,
    title: "Authentication UX Flows",
    slug: "authentication-ux-flows",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["auth", "login", "oauth", "mfa", "session"],
    relatedNFRs: [16, 42, 43],
    readTime: 10,
    importance: "high",
    tldr: "Design seamless authentication experiences with social login, MFA, session management, and secure token handling.",
  },
  {
    id: 18,
    title: "Third-Party Script Safety",
    slug: "third-party-script-safety",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["security", "third-party", "scripts", "sandboxing", "sri"],
    relatedNFRs: [15, 1, 62],
    readTime: 7,
    importance: "high",
    tldr: "Safely integrate third-party scripts with SRI, sandboxing, lazy loading, and performance monitoring.",
  },
  {
    id: 19,
    title: "State Management Strategy",
    slug: "state-management-strategy",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["state", "redux", "zustand", "context", "reactquery"],
    relatedNFRs: [20, 21, 23],
    readTime: 10,
    importance: "high",
    tldr: "Choose appropriate state management solutions for local, global, server, and URL state with proper separation.",
  },
  {
    id: 20,
    title: "Client Persistence Strategy",
    slug: "client-persistence-strategy",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["persistence", "indexeddb", "localstorage", "sync", "offline"],
    relatedNFRs: [6, 19, 21],
    readTime: 8,
    importance: "medium",
    tldr: "Implement client-side data persistence with IndexedDB, localStorage, and sync strategies for offline support.",
  },
  {
    id: 21,
    title: "Multi-Tab Synchronization",
    slug: "multi-tab-synchronization",
    category: "frontend",
    difficulty: "advanced",
    tags: ["tabs", "broadcast-channel", "sync", "shared-worker", "state"],
    relatedNFRs: [19, 20, 22],
    readTime: 8,
    importance: "medium",
    tldr: "Synchronize state across browser tabs using Broadcast Channel API, SharedWorker, or localStorage events.",
  },
  {
    id: 22,
    title: "Conflict Resolution UX",
    slug: "conflict-resolution-ux",
    category: "frontend",
    difficulty: "advanced",
    tags: ["conflicts", "merge", "optimistic-ui", "sync", "collaboration"],
    relatedNFRs: [21, 23, 70],
    readTime: 9,
    importance: "medium",
    tldr: "Handle data conflicts gracefully with merge strategies, user prompts, and automatic resolution patterns.",
  },
  {
    id: 23,
    title: "Real-Time UI Handling",
    slug: "real-time-ui-handling",
    category: "frontend",
    difficulty: "advanced",
    tags: ["realtime", "websocket", "sse", "polling", "live-updates"],
    relatedNFRs: [19, 22, 57],
    readTime: 10,
    importance: "high",
    tldr: "Implement real-time features with WebSockets, Server-Sent Events, or polling with proper connection management.",
  },
  {
    id: 24,
    title: "Frontend Testing Strategy",
    slug: "frontend-testing-strategy",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["testing", "unit", "integration", "e2e", "visual-regression"],
    relatedNFRs: [25, 26, 80],
    readTime: 11,
    importance: "high",
    tldr: "Build comprehensive testing pyramid with unit, integration, E2E, and visual regression tests for frontend.",
  },
  {
    id: 25,
    title: "Frontend Observability (RUM)",
    slug: "frontend-observability-rum",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["rum", "monitoring", "analytics", "errors", "performance"],
    relatedNFRs: [24, 63, 84],
    readTime: 9,
    importance: "high",
    tldr: "Implement Real User Monitoring (RUM) to track performance, errors, and user behavior in production.",
  },
  {
    id: 26,
    title: "Developer Experience (DX)",
    slug: "developer-experience",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["dx", "tooling", "hmr", "typescript", "linting"],
    relatedNFRs: [27, 72, 50],
    readTime: 8,
    importance: "high",
    tldr: "Optimize developer experience with fast builds, HMR, TypeScript, linting, and clear documentation.",
  },
  {
    id: 27,
    title: "Build Optimization",
    slug: "build-optimization",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["build", "bundling", "tree-shaking", "minification", "splitting"],
    relatedNFRs: [1, 26, 28],
    readTime: 9,
    importance: "high",
    tldr: "Optimize build process with tree-shaking, code splitting, minification, and efficient bundling strategies.",
  },
  {
    id: 28,
    title: "Frontend Deployment Strategy",
    slug: "frontend-deployment-strategy",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["deployment", "cdn", "ci-cd", "preview", "rollback"],
    relatedNFRs: [27, 50, 66],
    readTime: 8,
    importance: "high",
    tldr: "Deploy frontend assets with CI/CD, CDN distribution, preview environments, and instant rollback capabilities.",
  },
  {
    id: 29,
    title: "Privacy & Consent UX",
    slug: "privacy-consent-ux",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["privacy", "gdpr", "consent", "cookies", "tracking"],
    relatedNFRs: [67, 46, 16],
    readTime: 8,
    importance: "high",
    tldr: "Implement privacy-compliant consent management with clear UI, granular controls, and preference persistence.",
  },
  {
    id: 30,
    title: "Feature Flagging & Rollouts",
    slug: "feature-flagging-rollouts",
    category: "frontend",
    difficulty: "intermediate",
    tags: ["feature-flags", "rollout", "ab-testing", "toggles", "gradual"],
    relatedNFRs: [66, 81, 28],
    readTime: 9,
    importance: "high",
    tldr: "Control feature releases with feature flags, percentage rollouts, A/B testing, and kill switches.",
  },

  // ============================================
  // 🟨 BACKEND NFRs (31-60)
  // ============================================
  {
    id: 31,
    title: "Scalability Strategy",
    slug: "scalability-strategy",
    category: "backend",
    difficulty: "advanced",
    tags: ["scalability", "horizontal", "vertical", "auto-scaling", "elasticity"],
    relatedNFRs: [32, 34, 60],
    readTime: 12,
    importance: "critical",
    tldr: "Design systems that scale horizontally and vertically with auto-scaling, stateless services, and elastic infrastructure.",
  },
  {
    id: 32,
    title: "High Availability",
    slug: "high-availability",
    category: "backend",
    difficulty: "advanced",
    tags: ["availability", "redundancy", "failover", "clustering", "uptime"],
    relatedNFRs: [31, 33, 68],
    readTime: 11,
    importance: "critical",
    tldr: "Achieve high availability with redundancy, automatic failover, health checks, and multi-AZ deployments.",
  },
  {
    id: 33,
    title: "Fault Tolerance & Resilience",
    slug: "fault-tolerance-resilience",
    category: "backend",
    difficulty: "advanced",
    tags: ["resilience", "circuit-breaker", "retry", "bulkhead", "fallback"],
    relatedNFRs: [32, 53, 83],
    readTime: 12,
    importance: "critical",
    tldr: "Build resilient systems with circuit breakers, retries with backoff, bulkheads, and graceful degradation.",
  },
  {
    id: 34,
    title: "Throughput Capacity",
    slug: "throughput-capacity",
    category: "backend",
    difficulty: "intermediate",
    tags: ["throughput", "capacity", "rps", "benchmarking", "load-testing"],
    relatedNFRs: [31, 35, 60],
    readTime: 9,
    importance: "high",
    tldr: "Measure and optimize system throughput with load testing, capacity planning, and performance tuning.",
  },
  {
    id: 35,
    title: "Latency SLAs",
    slug: "latency-slas",
    category: "backend",
    difficulty: "intermediate",
    tags: ["latency", "sla", "p99", "response-time", "optimization"],
    relatedNFRs: [34, 68, 84],
    readTime: 8,
    importance: "high",
    tldr: "Define and meet latency SLAs with P99 targets, optimization techniques, and continuous monitoring.",
  },
  {
    id: 36,
    title: "Consistency Model",
    slug: "consistency-model",
    category: "backend",
    difficulty: "advanced",
    tags: ["consistency", "eventual", "strong", "cap-theorem", "distributed"],
    relatedNFRs: [37, 70, 56],
    readTime: 11,
    importance: "high",
    tldr: "Choose appropriate consistency models (strong, eventual, causal) based on CAP theorem trade-offs.",
  },
  {
    id: 37,
    title: "Durability Guarantees",
    slug: "durability-guarantees",
    category: "backend",
    difficulty: "intermediate",
    tags: ["durability", "persistence", "backup", "replication", "wal"],
    relatedNFRs: [36, 40, 49],
    readTime: 9,
    importance: "critical",
    tldr: "Ensure data durability with write-ahead logging, replication, backups, and proper storage configuration.",
  },
  {
    id: 38,
    title: "Database Selection Strategy",
    slug: "database-selection-strategy",
    category: "backend",
    difficulty: "advanced",
    tags: ["database", "sql", "nosql", "polyglot", "selection"],
    relatedNFRs: [36, 37, 39],
    readTime: 12,
    importance: "high",
    tldr: "Select appropriate databases (SQL, NoSQL, NewSQL) based on data model, query patterns, and scalability needs.",
  },
  {
    id: 39,
    title: "Server-Side Caching Strategy",
    slug: "server-side-caching-strategy",
    category: "backend",
    difficulty: "intermediate",
    tags: ["caching", "redis", "memcached", "invalidation", "ttl"],
    relatedNFRs: [38, 69, 7],
    readTime: 10,
    importance: "high",
    tldr: "Implement multi-layer server caching with Redis/Memcached, proper invalidation, and cache-aside patterns.",
  },
  {
    id: 40,
    title: "Data Retention & Archival",
    slug: "data-retention-archival",
    category: "backend",
    difficulty: "intermediate",
    tags: ["retention", "archival", "compliance", "lifecycle", "cold-storage"],
    relatedNFRs: [37, 46, 67],
    readTime: 8,
    importance: "high",
    tldr: "Define data retention policies with automated archival, compliance requirements, and cost-effective cold storage.",
  },
  {
    id: 41,
    title: "Data Migration Strategy",
    slug: "data-migration-strategy",
    category: "backend",
    difficulty: "advanced",
    tags: ["migration", "schema", "zero-downtime", "rollback", "versioning"],
    relatedNFRs: [58, 65, 73],
    readTime: 11,
    importance: "high",
    tldr: "Execute safe data migrations with zero-downtime techniques, rollback plans, and schema versioning.",
  },
  {
    id: 42,
    title: "Authentication Infrastructure",
    slug: "authentication-infrastructure",
    category: "backend",
    difficulty: "intermediate",
    tags: ["auth", "oauth", "jwt", "sso", "identity"],
    relatedNFRs: [43, 17, 45],
    readTime: 11,
    importance: "critical",
    tldr: "Build secure authentication with OAuth2, JWT, SSO integration, and identity provider management.",
  },
  {
    id: 43,
    title: "Authorization Model",
    slug: "authorization-model",
    category: "backend",
    difficulty: "intermediate",
    tags: ["authorization", "rbac", "abac", "permissions", "policies"],
    relatedNFRs: [42, 82, 46],
    readTime: 10,
    importance: "critical",
    tldr: "Implement fine-grained authorization with RBAC, ABAC, or policy-based access control systems.",
  },
  {
    id: 44,
    title: "Rate Limiting & Abuse Protection",
    slug: "rate-limiting-abuse-protection",
    category: "backend",
    difficulty: "intermediate",
    tags: ["rate-limiting", "throttling", "ddos", "abuse", "quotas"],
    relatedNFRs: [59, 62, 33],
    readTime: 9,
    importance: "critical",
    tldr: "Protect APIs with rate limiting, request throttling, DDoS mitigation, and abuse detection systems.",
  },
  {
    id: 45,
    title: "Secrets Management",
    slug: "secrets-management",
    category: "backend",
    difficulty: "intermediate",
    tags: ["secrets", "vault", "rotation", "encryption", "env-vars"],
    relatedNFRs: [42, 62, 16],
    readTime: 8,
    importance: "critical",
    tldr: "Securely manage secrets with vault solutions, automatic rotation, encryption at rest, and secure injection.",
  },
  {
    id: 46,
    title: "Compliance & Auditing",
    slug: "compliance-auditing",
    category: "backend",
    difficulty: "intermediate",
    tags: ["compliance", "audit", "gdpr", "hipaa", "soc2"],
    relatedNFRs: [40, 67, 85],
    readTime: 10,
    importance: "high",
    tldr: "Implement compliance controls for GDPR, HIPAA, SOC2 with comprehensive audit logging and data governance.",
  },
  {
    id: 47,
    title: "Centralized Logging",
    slug: "centralized-logging",
    category: "backend",
    difficulty: "intermediate",
    tags: ["logging", "elk", "structured", "aggregation", "correlation"],
    relatedNFRs: [48, 63, 71],
    readTime: 9,
    importance: "high",
    tldr: "Aggregate logs centrally with structured logging, correlation IDs, and searchable log management.",
  },
  {
    id: 48,
    title: "Metrics & Distributed Tracing",
    slug: "metrics-distributed-tracing",
    category: "backend",
    difficulty: "advanced",
    tags: ["metrics", "tracing", "prometheus", "jaeger", "opentelemetry"],
    relatedNFRs: [47, 63, 84],
    readTime: 11,
    importance: "high",
    tldr: "Implement observability with metrics collection, distributed tracing, and OpenTelemetry instrumentation.",
  },
  {
    id: 49,
    title: "Disaster Recovery Strategy",
    slug: "disaster-recovery-strategy",
    category: "backend",
    difficulty: "advanced",
    tags: ["dr", "backup", "rto", "rpo", "failover"],
    relatedNFRs: [32, 37, 56],
    readTime: 12,
    importance: "critical",
    tldr: "Plan for disasters with defined RTO/RPO, automated backups, cross-region failover, and recovery testing.",
  },
  {
    id: 50,
    title: "CI/CD Pipelines",
    slug: "cicd-pipelines",
    category: "backend",
    difficulty: "intermediate",
    tags: ["cicd", "automation", "deployment", "testing", "pipelines"],
    relatedNFRs: [28, 73, 66],
    readTime: 10,
    importance: "high",
    tldr: "Automate build, test, and deployment with CI/CD pipelines, quality gates, and deployment strategies.",
  },
  {
    id: 51,
    title: "Cost Optimization",
    slug: "cost-optimization",
    category: "backend",
    difficulty: "intermediate",
    tags: ["cost", "optimization", "rightsizing", "reserved", "spot"],
    relatedNFRs: [31, 60, 39],
    readTime: 9,
    importance: "high",
    tldr: "Optimize cloud costs with rightsizing, reserved instances, spot usage, and resource lifecycle management.",
  },
  {
    id: 52,
    title: "API Versioning",
    slug: "api-versioning",
    category: "backend",
    difficulty: "intermediate",
    tags: ["api", "versioning", "backward-compatibility", "deprecation", "migration"],
    relatedNFRs: [65, 58, 72],
    readTime: 8,
    importance: "high",
    tldr: "Implement API versioning with backward compatibility, clear deprecation policies, and migration paths.",
  },
  {
    id: 53,
    title: "Backpressure Handling",
    slug: "backpressure-handling",
    category: "backend",
    difficulty: "advanced",
    tags: ["backpressure", "flow-control", "queuing", "throttling", "reactive"],
    relatedNFRs: [33, 59, 34],
    readTime: 9,
    importance: "high",
    tldr: "Handle system overload with backpressure mechanisms, flow control, and adaptive load shedding.",
  },
  {
    id: 54,
    title: "Idempotency Guarantees",
    slug: "idempotency-guarantees",
    category: "backend",
    difficulty: "intermediate",
    tags: ["idempotency", "retry", "deduplication", "exactly-once", "api"],
    relatedNFRs: [55, 33, 70],
    readTime: 8,
    importance: "high",
    tldr: "Ensure idempotent operations with idempotency keys, deduplication, and safe retry semantics.",
  },
  {
    id: 55,
    title: "Event Replayability",
    slug: "event-replayability",
    category: "backend",
    difficulty: "advanced",
    tags: ["events", "replay", "event-sourcing", "audit", "recovery"],
    relatedNFRs: [54, 57, 85],
    readTime: 10,
    importance: "medium",
    tldr: "Enable event replay for debugging, recovery, and audit with event sourcing and immutable event logs.",
  },
  {
    id: 56,
    title: "Multi-Region Replication",
    slug: "multi-region-replication",
    category: "backend",
    difficulty: "advanced",
    tags: ["replication", "multi-region", "geo", "latency", "consistency"],
    relatedNFRs: [32, 36, 49],
    readTime: 13,
    importance: "high",
    tldr: "Deploy across regions for low latency and disaster recovery with data replication and conflict resolution.",
  },
  {
    id: 57,
    title: "Message Ordering Guarantees",
    slug: "message-ordering-guarantees",
    category: "backend",
    difficulty: "advanced",
    tags: ["messaging", "ordering", "kafka", "partitions", "sequence"],
    relatedNFRs: [55, 23, 36],
    readTime: 9,
    importance: "high",
    tldr: "Guarantee message ordering with partitioning strategies, sequence numbers, and ordered processing.",
  },
  {
    id: 58,
    title: "Schema Governance",
    slug: "schema-governance",
    category: "backend",
    difficulty: "intermediate",
    tags: ["schema", "governance", "registry", "evolution", "compatibility"],
    relatedNFRs: [52, 41, 65],
    readTime: 8,
    importance: "high",
    tldr: "Manage schema evolution with registries, compatibility checks, and versioning policies.",
  },
  {
    id: 59,
    title: "Traffic Management / Load Shedding",
    slug: "traffic-management-load-shedding",
    category: "backend",
    difficulty: "advanced",
    tags: ["traffic", "load-shedding", "priority", "degradation", "throttling"],
    relatedNFRs: [44, 53, 33],
    readTime: 10,
    importance: "high",
    tldr: "Manage traffic spikes with load shedding, priority queuing, and graceful degradation strategies.",
  },
  {
    id: 60,
    title: "Capacity Planning",
    slug: "capacity-planning",
    category: "backend",
    difficulty: "intermediate",
    tags: ["capacity", "planning", "forecasting", "growth", "resources"],
    relatedNFRs: [31, 34, 51],
    readTime: 9,
    importance: "high",
    tldr: "Plan infrastructure capacity with growth forecasting, resource modeling, and proactive scaling.",
  },

  // ============================================
  // 🟪 SHARED / CROSS-CUTTING NFRs (61-75)
  // ============================================
  {
    id: 61,
    title: "End-to-End Performance Budgets",
    slug: "e2e-performance-budgets",
    category: "shared",
    difficulty: "intermediate",
    tags: ["performance", "budgets", "sla", "monitoring", "alerts"],
    relatedNFRs: [1, 35, 84],
    readTime: 8,
    importance: "high",
    tldr: "Define and enforce performance budgets across the stack with automated monitoring and alerting.",
  },
  {
    id: 62,
    title: "End-to-End Security Posture",
    slug: "e2e-security-posture",
    category: "shared",
    difficulty: "advanced",
    tags: ["security", "defense-in-depth", "zero-trust", "scanning", "audit"],
    relatedNFRs: [15, 45, 46],
    readTime: 12,
    importance: "critical",
    tldr: "Implement defense-in-depth security with zero-trust architecture, continuous scanning, and security audits.",
  },
  {
    id: 63,
    title: "End-to-End Observability",
    slug: "e2e-observability",
    category: "shared",
    difficulty: "advanced",
    tags: ["observability", "logs", "metrics", "traces", "correlation"],
    relatedNFRs: [25, 47, 48],
    readTime: 11,
    importance: "high",
    tldr: "Achieve full-stack observability with correlated logs, metrics, and traces across all services.",
  },
  {
    id: 64,
    title: "Error Handling & Recovery Strategy",
    slug: "error-handling-recovery-strategy",
    category: "shared",
    difficulty: "intermediate",
    tags: ["errors", "recovery", "retry", "compensation", "saga"],
    relatedNFRs: [14, 33, 71],
    readTime: 9,
    importance: "high",
    tldr: "Design consistent error handling with recovery patterns, compensation logic, and saga orchestration.",
  },
  {
    id: 65,
    title: "Versioning & Backward Compatibility",
    slug: "versioning-backward-compatibility",
    category: "shared",
    difficulty: "intermediate",
    tags: ["versioning", "compatibility", "semver", "deprecation", "migration"],
    relatedNFRs: [52, 58, 73],
    readTime: 8,
    importance: "high",
    tldr: "Maintain backward compatibility with semantic versioning, deprecation policies, and smooth migrations.",
  },
  {
    id: 66,
    title: "Feature Rollout Strategy",
    slug: "feature-rollout-strategy",
    category: "shared",
    difficulty: "intermediate",
    tags: ["rollout", "canary", "blue-green", "progressive", "feature-flags"],
    relatedNFRs: [30, 81, 50],
    readTime: 9,
    importance: "high",
    tldr: "Roll out features safely with canary deployments, blue-green, and progressive delivery strategies.",
  },
  {
    id: 67,
    title: "Privacy & Data Governance",
    slug: "privacy-data-governance",
    category: "shared",
    difficulty: "intermediate",
    tags: ["privacy", "gdpr", "data-governance", "pii", "consent"],
    relatedNFRs: [29, 46, 85],
    readTime: 10,
    importance: "critical",
    tldr: "Govern data privacy with PII handling, consent management, and regulatory compliance frameworks.",
  },
  {
    id: 68,
    title: "Availability SLAs",
    slug: "availability-slas",
    category: "shared",
    difficulty: "intermediate",
    tags: ["availability", "sla", "uptime", "nines", "monitoring"],
    relatedNFRs: [32, 35, 84],
    readTime: 8,
    importance: "critical",
    tldr: "Define and maintain availability SLAs with uptime targets, monitoring, and incident response.",
  },
  {
    id: 69,
    title: "Caching Consistency Strategy",
    slug: "caching-consistency-strategy",
    category: "shared",
    difficulty: "advanced",
    tags: ["caching", "consistency", "invalidation", "coherence", "distributed"],
    relatedNFRs: [7, 39, 70],
    readTime: 10,
    importance: "high",
    tldr: "Maintain cache consistency across layers with invalidation strategies and coherence protocols.",
  },
  {
    id: 70,
    title: "Data Consistency Guarantees",
    slug: "data-consistency-guarantees",
    category: "shared",
    difficulty: "advanced",
    tags: ["consistency", "transactions", "distributed", "conflict", "resolution"],
    relatedNFRs: [36, 22, 69],
    readTime: 11,
    importance: "high",
    tldr: "Ensure data consistency across services with distributed transactions and conflict resolution.",
  },
  {
    id: 71,
    title: "Incident Response & On-call Readiness",
    slug: "incident-response-oncall",
    category: "shared",
    difficulty: "intermediate",
    tags: ["incident", "oncall", "runbooks", "escalation", "postmortem"],
    relatedNFRs: [63, 64, 47],
    readTime: 9,
    importance: "high",
    tldr: "Prepare for incidents with runbooks, escalation paths, on-call rotations, and blameless postmortems.",
  },
  {
    id: 72,
    title: "Documentation Quality",
    slug: "documentation-quality",
    category: "shared",
    difficulty: "beginner",
    tags: ["documentation", "api-docs", "readme", "adr", "wiki"],
    relatedNFRs: [26, 52, 73],
    readTime: 7,
    importance: "high",
    tldr: "Maintain quality documentation with API specs, architecture decisions, and up-to-date guides.",
  },
  {
    id: 73,
    title: "Change Management",
    slug: "change-management",
    category: "shared",
    difficulty: "intermediate",
    tags: ["change", "review", "approval", "rollback", "audit"],
    relatedNFRs: [50, 65, 41],
    readTime: 8,
    importance: "high",
    tldr: "Manage changes safely with review processes, approval workflows, and audit trails.",
  },
  {
    id: 74,
    title: "Dependency Management",
    slug: "dependency-management",
    category: "shared",
    difficulty: "intermediate",
    tags: ["dependencies", "vulnerabilities", "updates", "lockfiles", "scanning"],
    relatedNFRs: [62, 50, 26],
    readTime: 8,
    importance: "high",
    tldr: "Manage dependencies with vulnerability scanning, automated updates, and version pinning.",
  },
  {
    id: 75,
    title: "Vendor Lock-in Strategy",
    slug: "vendor-lock-in-strategy",
    category: "shared",
    difficulty: "intermediate",
    tags: ["vendor", "portability", "abstraction", "multi-cloud", "standards"],
    relatedNFRs: [38, 51, 65],
    readTime: 8,
    importance: "medium",
    tldr: "Minimize vendor lock-in with abstraction layers, open standards, and multi-cloud strategies.",
  },

  // ============================================
  // 🟩 ADVANCED / BONUS NFRs (76-85)
  // ============================================
  {
    id: 76,
    title: "Memory Management (Frontend Leaks)",
    slug: "memory-management-frontend",
    category: "advanced",
    difficulty: "advanced",
    tags: ["memory", "leaks", "profiling", "gc", "detached-dom"],
    relatedNFRs: [4, 1, 25],
    readTime: 10,
    importance: "high",
    tldr: "Detect and fix frontend memory leaks with profiling, proper cleanup, and avoiding detached DOM nodes.",
  },
  {
    id: 77,
    title: "Battery & CPU Efficiency (Mobile)",
    slug: "battery-cpu-efficiency",
    category: "advanced",
    difficulty: "advanced",
    tags: ["battery", "cpu", "mobile", "efficiency", "background"],
    relatedNFRs: [11, 76, 1],
    readTime: 9,
    importance: "medium",
    tldr: "Optimize for mobile battery and CPU with efficient animations, background task management, and wake locks.",
  },
  {
    id: 78,
    title: "Micro-Frontend Compatibility",
    slug: "micro-frontend-compatibility",
    category: "advanced",
    difficulty: "advanced",
    tags: ["micro-frontend", "federation", "isolation", "shared-deps", "routing"],
    relatedNFRs: [19, 27, 65],
    readTime: 12,
    importance: "medium",
    tldr: "Build micro-frontend architectures with module federation, shared dependencies, and isolated deployments.",
  },
  {
    id: 79,
    title: "Progressive Enhancement",
    slug: "progressive-enhancement",
    category: "advanced",
    difficulty: "intermediate",
    tags: ["progressive", "enhancement", "graceful", "no-js", "baseline"],
    relatedNFRs: [10, 9, 11],
    readTime: 8,
    importance: "medium",
    tldr: "Build with progressive enhancement for baseline functionality without JavaScript and enhanced experiences.",
  },
  {
    id: 80,
    title: "Accessibility Automation",
    slug: "accessibility-automation",
    category: "advanced",
    difficulty: "intermediate",
    tags: ["a11y", "automation", "testing", "axe", "ci"],
    relatedNFRs: [9, 24, 50],
    readTime: 8,
    importance: "high",
    tldr: "Automate accessibility testing in CI/CD with axe-core, Lighthouse, and continuous monitoring.",
  },
  {
    id: 81,
    title: "Canary Experimentation Framework",
    slug: "canary-experimentation-framework",
    category: "advanced",
    difficulty: "advanced",
    tags: ["canary", "experimentation", "ab-testing", "metrics", "rollout"],
    relatedNFRs: [30, 66, 84],
    readTime: 11,
    importance: "medium",
    tldr: "Build experimentation platforms with canary analysis, A/B testing, and metric-driven rollout decisions.",
  },
  {
    id: 82,
    title: "Multi-Tenant Isolation",
    slug: "multi-tenant-isolation",
    category: "advanced",
    difficulty: "advanced",
    tags: ["multi-tenant", "isolation", "saas", "security", "resources"],
    relatedNFRs: [43, 62, 31],
    readTime: 12,
    importance: "high",
    tldr: "Isolate tenants with data separation, resource quotas, and security boundaries in multi-tenant systems.",
  },
  {
    id: 83,
    title: "Chaos Testing",
    slug: "chaos-testing",
    category: "advanced",
    difficulty: "advanced",
    tags: ["chaos", "resilience", "failure-injection", "gameday", "testing"],
    relatedNFRs: [33, 71, 49],
    readTime: 10,
    importance: "medium",
    tldr: "Practice chaos engineering with controlled failure injection, game days, and resilience validation.",
  },
  {
    id: 84,
    title: "SLO / Error Budget Management",
    slug: "slo-error-budget-management",
    category: "advanced",
    difficulty: "advanced",
    tags: ["slo", "sli", "error-budget", "reliability", "targets"],
    relatedNFRs: [68, 35, 48],
    readTime: 10,
    importance: "high",
    tldr: "Define SLOs and manage error budgets to balance reliability with development velocity.",
  },
  {
    id: 85,
    title: "Data Lineage & Auditability",
    slug: "data-lineage-auditability",
    category: "advanced",
    difficulty: "advanced",
    tags: ["lineage", "audit", "provenance", "tracking", "compliance"],
    relatedNFRs: [46, 55, 67],
    readTime: 10,
    importance: "high",
    tldr: "Track data lineage and provenance for auditability, debugging, and compliance requirements.",
  },
];

// Helper functions
export const getNFRById = (id: number): NFRMetadata | undefined => {
  return NFR_METADATA.find((nfr) => nfr.id === id);
};

export const getNFRBySlug = (slug: string): NFRMetadata | undefined => {
  return NFR_METADATA.find((nfr) => nfr.slug === slug);
};

export const getNFRsByCategory = (category: NFRCategory): NFRMetadata[] => {
  return NFR_METADATA.filter((nfr) => nfr.category === category);
};

export const getNFRsByTag = (tag: string): NFRMetadata[] => {
  return NFR_METADATA.filter((nfr) => nfr.tags.includes(tag));
};

export const getRelatedNFRs = (id: number): NFRMetadata[] => {
  const nfr = getNFRById(id);
  if (!nfr) return [];
  return nfr.relatedNFRs
    .map((relatedId) => getNFRById(relatedId))
    .filter((n): n is NFRMetadata => n !== undefined);
};

export const getAllTags = (): string[] => {
  const tags = new Set<string>();
  NFR_METADATA.forEach((nfr) => nfr.tags.forEach((tag) => tags.add(tag)));
  return Array.from(tags).sort();
};

export const getFeaturedNFRs = (count: number = 5): NFRMetadata[] => {
  // Return NFRs with critical importance first, then by ID
  return [...NFR_METADATA]
    .sort((a, b) => {
      const importanceOrder = { critical: 0, high: 1, medium: 2 };
      const diff = importanceOrder[a.importance] - importanceOrder[b.importance];
      return diff !== 0 ? diff : a.id - b.id;
    })
    .slice(0, count);
};
